
services:

  postgres-price-db:
    image: postgres:15
    environment:
      POSTGRES_DB: price-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
    ports:
      - "5432:5432"
    networks:
      - price-service-network



  price-service:
    build: .
    container_name: price-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-price-db
    environment:
      DB_HOST: postgres-price-db
      DB_NAME: price-db
      DB_USERNAME: postgres
      DB_PASSWORD: passer
      RABBIT_HOST: rabbitmq
      REDIS_HOST: redis-server
    networks:
      - price-service-network
      - regulation-platform-network

# Definition des networks
networks:
  # Network commune a tous les microservices
  regulation-platform-network:
    external: true
  # Network interne pour chaque ms permettant la connexion entre les container d'un ms
  price-service-network: